language: c
compiler: gcc
script:
  - bash ./util/build_and_test.bash

# See: https://github.com/chapel-lang/chapel/blob/master/.travis.yml#L8
env:
  - QTHREAD_AFFINITY=no
addons:
  apt:
    packages:
      - tcsh
sudo: false
